# Generated by Django 5.2.17 on 2026-08-07 05:32

import django.db.models.deletion
import quantem.segmentation.instance_params
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('long_name', models.CharField(max_length=100, unique=True)),
                ('default_color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'ordering': ['long_name'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationTypeTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageSegmentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_stage', models.CharField(choices=[('UNSTARTED', 'Unstarted'), ('RUNNING_INFERENCE', 'Running inference'), ('EXTRACTING_CANDIDATES', 'Extracting candidates'), ('CANDIDATES_READY', 'Candidates ready'), ('UPDATING', 'Updating with feedback'), ('COMPUTING_FEATURES', 'Computing features'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UNSTARTED', max_length=50)),
                ('status_progress', models.FloatField(default=0.0)),
                ('status_error', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segmentations', to='assets.asset')),
                ('segmentation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_segmentations', to='segmentation.segmentationtype')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProbabilityMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('channel_index', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probability_maps', to='segmentation.imagesegmentation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_params', models.JSONField(blank=True, default=quantem.segmentation.instance_params.instance_params_defaults)),
                ('segmentation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='segmentation.imagesegmentation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationOverlayState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_source_model', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('MISSING', 'Missing'), ('READY', 'Ready'), ('DIRTY', 'Dirty'), ('BUILDING', 'Building'), ('FAILED', 'Failed')], default='MISSING', max_length=16)),
                ('bundle_version', models.PositiveIntegerField(default=0)),
                ('applied_revision', models.PositiveIntegerField(default=0)),
                ('desired_revision', models.PositiveIntegerField(default=0)),
                ('lut_revision', models.PositiveIntegerField(default=0)),
                ('pending_full_rebuild', models.BooleanField(default=False)),
                ('dirty_chunk_runs', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_states', to='segmentation.imagesegmentation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationOverlayLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.PositiveIntegerField()),
                ('object_uuid', models.UUIDField()),
                ('overlay_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='segmentation.segmentationoverlaystate')),
            ],
        ),
        migrations.AddField(
            model_name='segmentationtype',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='segmentation_types', to='segmentation.segmentationtypetag'),
        ),
        migrations.CreateModel(
            name='SegmentObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometry_wkb', models.BinaryField()),
                ('centroid_x', models.FloatField()),
                ('centroid_y', models.FloatField()),
                ('bbox_minx', models.FloatField()),
                ('bbox_miny', models.FloatField()),
                ('bbox_maxx', models.FloatField()),
                ('bbox_maxy', models.FloatField()),
                ('label_state', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('EXCLUDED', 'Excluded'), ('INFERRED', 'Inferred'), ('CANDIDATE', 'Candidate')], default='INFERRED', max_length=10)),
                ('refined', models.CharField(choices=[('UNREFINED', 'Unrefined'), ('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='UNREFINED', max_length=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'CANDIDATE'), (1, 'CONFIRMED'), (10, 'REFINED')], default=0)),
                ('source_model', models.CharField(db_index=True, default='unknown', max_length=128)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('base_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_segments', to='segmentation.segmentobject')),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='segmentation.imagesegmentation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_type', models.CharField(choices=[('point', 'Point'), ('polygon', 'Polygon')], default='point', max_length=16)),
                ('pt_x', models.FloatField(blank=True, null=True)),
                ('pt_y', models.FloatField(blank=True, null=True)),
                ('polygon_wkb', models.BinaryField(blank=True, null=True)),
                ('feedback_type', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], max_length=16)),
                ('utilized_status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='QUEUED', max_length=16)),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to='segmentation.imagesegmentation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompletedROI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometry_wkb', models.BinaryField()),
                ('bbox_minx', models.FloatField()),
                ('bbox_miny', models.FloatField()),
                ('bbox_maxx', models.FloatField()),
                ('bbox_maxy', models.FloatField()),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_rois', to='segmentation.imagesegmentation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['segmentation'], name='segmentatio_segment_162fc3_idx'), models.Index(fields=['segmentation', 'bbox_minx', 'bbox_maxx'], name='segmentatio_segment_9360e7_idx'), models.Index(fields=['segmentation', 'bbox_miny', 'bbox_maxy'], name='segmentatio_segment_3b462b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoiSegmentationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('image_roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_statuses', to='assets.imageroi')),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_statuses', to='segmentation.imagesegmentation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['segmentation', 'is_complete'], name='segmentatio_segment_d9eb16_idx'), models.Index(fields=['image_roi'], name='segmentatio_image_r_98e297_idx')],
                'constraints': [models.UniqueConstraint(fields=('image_roi', 'segmentation'), name='uniq_roi_segmentation_status')],
            },
        ),
        migrations.AddIndex(
            model_name='segmentationoverlaystate',
            index=models.Index(fields=['segmentation', 'candidate_source_model'], name='segmentatio_segment_b1c8b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='segmentationoverlaystate',
            constraint=models.UniqueConstraint(fields=('segmentation', 'candidate_source_model'), name='unique_overlay_state_per_segmentation_source'),
        ),
        migrations.AddIndex(
            model_name='segmentationoverlaylabel',
            index=models.Index(fields=['overlay_state', 'label'], name='seg_ovl_label_state_lbl_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentationoverlaylabel',
            index=models.Index(fields=['overlay_state', 'object_uuid'], name='seg_ovl_label_state_uuid_idx'),
        ),
        migrations.AddConstraint(
            model_name='segmentationoverlaylabel',
            constraint=models.UniqueConstraint(fields=('overlay_state', 'label'), name='unique_overlay_label_per_state'),
        ),
        migrations.AddConstraint(
            model_name='imagesegmentation',
            constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False)), fields=('asset', 'segmentation_type'), name='unique_segmentation_per_asset'),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'label_state'], name='segmentatio_segment_1e9596_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'confidence_score'], name='segmentatio_segment_aeeb7f_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'refined'], name='segmentatio_segment_1e9165_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'source_model', 'status'], name='segmentatio_segment_4920f3_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'source_model', 'label_state'], name='segmentatio_segment_bb9095_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'bbox_minx', 'bbox_maxx'], name='segmentatio_segment_e5155d_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'bbox_miny', 'bbox_maxy'], name='segmentatio_segment_710b26_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'centroid_x', 'centroid_y'], name='segmentatio_segment_4d3594_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['segmentation', 'utilized_status'], name='segmentatio_segment_0b26f2_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['segmentation', 'feedback_type'], name='segmentatio_segment_dfc23b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfeedback',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('input_type', 'point'), _negated=True), models.Q(('pt_x__isnull', False), ('pt_y__isnull', False)), _connector='OR'), name='user_feedback_point_requires_coordinates'),
        ),
        migrations.AddConstraint(
            model_name='userfeedback',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('input_type', 'polygon'), _negated=True), ('polygon_wkb__isnull', False), _connector='OR'), name='user_feedback_polygon_requires_polygon'),
        ),
    ]
