# Generated by Django 5.2.17 on 2026-08-07 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationCompletionArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discarded_count', models.PositiveIntegerField(default=0)),
                ('objects_json', models.JSONField(blank=True, default=list)),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_archives', to='segmentation.imagesegmentation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['segmentation', '-created_at'], name='segmentatio_segment_33c4d0_idx')],
            },
        ),
    ]
