# Generated by Django 5.2.17 on 2026-08-10 19:10
"""The one segmentation migration for the v2 push.

**Why one file for five features.** Nine packages were built in parallel over
this app's models. Nine migrations authored in nine working copies would each
name ``0002`` as their parent, and the first two to merge would leave the tree
with two heads and every later one wrong about what already exists. So this is
authored once, up front, containing every column any package needs -- including
columns whose *code* lands later, in another package's commit. A column with no
code yet is inert; two competing migrations are not.

What is here, and who asked for it:

============================================  ==========================
``QualityCheck``, ``CountBox``                the two-number quality answer
``SegmentObject.run_version``                 result versions
``SegmentObject.superseded_at``               result versions
``SegmentationResultVersion``                 result versions
``ImageSegmentation.preview_rows_ready``      the live preview wash
``ImageSegmentation.include_level``           the include-level dial
``ProbabilityMap.grid``                       native-coordinate probability
``ProbabilityMap.quantisation``               native-coordinate probability
``ProbabilityMap.resample_kernel``            native-coordinate probability
``ProbabilityMap.value_range``                native-coordinate probability
============================================  ==========================

**Every added column is nullable or has a default**, so a half-landed push --
new schema, old code, or new code against a database that has not migrated yet
-- never leaves a running server unable to write a row.

**It reverses.** Every operation here has an inverse, including the one data
step, and that is asserted against a database holding real rows by
``segmentation/tests/test_migration_roundtrip.py``. Reversing drops the four
probability-map provenance columns, so the backfill's inverse is a no-op rather
than an attempt to put values back into columns that no longer exist.
"""

import django.db.models.deletion
import uuid
from django.db import migrations, models

#: Metadata keys ``inference`` already records beside a stored probability map,
#: read by :func:`backfill_probability_map_provenance` so a map written before
#: these columns existed is described by what it actually recorded rather than
#: by the column defaults. Spelled with a ``z`` because that is how the
#: inference layer spells them; the columns use the ``s`` spelling the rest of
#: this codebase uses, and this is the one place the two meet.
_META_NATIVE = "native_coordinates"
_META_INTERPOLATION = "resample_interpolation"
_META_QUANTIZATION = "quantization"
_META_QUANTIZATION_LEVELS = "quantization_levels"

#: The float interval a full-scale quantised map stands for. Applied only where
#: the row actually recorded a quantisation scheme -- a row that recorded none
#: keeps ``value_range = NULL``, which says "not recorded" rather than claiming
#: a range nobody wrote down.
_FULL_VALUE_RANGE = [0.0, 1.0]


def backfill_probability_map_provenance(apps, schema_editor):
    """Describe existing probability maps from their own recorded metadata.

    The column defaults are already right for every map this application has
    ever written -- the stored array has always been at native scale, and it
    has always been uint8 -- so this is not a repair. It is a promotion: rows
    written since the inference layer started recording the interpolator and
    the quantisation scheme can say *which* interpolator and *which* scheme,
    and leaving that in a JSON blob when there is now a column for it would
    make two records of the same fact that can disagree.

    Rows with nothing recorded are left on the defaults, and their
    ``resample_kernel`` stays blank and ``value_range`` stays null: unknown,
    stated as unknown.
    """
    ProbabilityMap = apps.get_model("segmentation", "ProbabilityMap")
    updated = []
    for row in ProbabilityMap.objects.all().iterator():
        metadata = row.metadata if isinstance(row.metadata, dict) else {}
        if not metadata:
            continue
        changed = False

        native = metadata.get(_META_NATIVE)
        if native is False:
            row.grid = "model"
            changed = True

        interpolation = metadata.get(_META_INTERPOLATION)
        if isinstance(interpolation, str) and interpolation.strip():
            row.resample_kernel = interpolation.strip()[:32]
            changed = True

        quantization = metadata.get(_META_QUANTIZATION)
        if isinstance(quantization, str) and quantization.strip():
            row.quantisation = quantization.strip()[:16]
            changed = True

        if quantization or metadata.get(_META_QUANTIZATION_LEVELS):
            row.value_range = list(_FULL_VALUE_RANGE)
            changed = True

        if changed:
            updated.append(row)
        if len(updated) >= 500:
            ProbabilityMap.objects.bulk_update(
                updated, ["grid", "quantisation", "resample_kernel", "value_range"]
            )
            updated = []
    if updated:
        ProbabilityMap.objects.bulk_update(
            updated, ["grid", "quantisation", "resample_kernel", "value_range"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_segmentationcompletionarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_version', models.PositiveIntegerField(default=1)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('seed', models.BigIntegerField(default=0)),
                ('placement', models.CharField(blank=True, default='', max_length=16)),
                ('n_marked', models.PositiveIntegerField(default=0)),
                ('n_matched', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['segmentation', 'run_version'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('random_sample', 'Random spot check'), ('count_box', 'Inside the count box')], default='random_sample', max_length=16)),
                ('sample_seed', models.BigIntegerField(default=0)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('answer', models.CharField(blank=True, choices=[('yes', 'Yes'), ('wrong_shape', 'Wrong shape'), ('not_the_thing', 'Not the thing'), ('unsure', 'Not sure')], default='', max_length=16)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['segmentation', 'run_version', 'kind', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationResultVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('include_level', models.FloatField(blank=True, null=True)),
                ('run_identity', models.JSONField(blank=True, default=dict)),
                ('object_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['segmentation', 'version'],
            },
        ),
        migrations.AddField(
            model_name='imagesegmentation',
            name='include_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagesegmentation',
            name='preview_rows_ready',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probabilitymap',
            name='grid',
            field=models.CharField(choices=[('native', 'Original image pixels'), ('model', 'Model prediction grid')], default='native', max_length=16),
        ),
        migrations.AddField(
            model_name='probabilitymap',
            name='quantisation',
            field=models.CharField(default='uint8', max_length=16),
        ),
        migrations.AddField(
            model_name='probabilitymap',
            name='resample_kernel',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='probabilitymap',
            name='value_range',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentobject',
            name='run_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='segmentobject',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'superseded_at'], name='segmentatio_segment_87d7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentobject',
            index=models.Index(fields=['segmentation', 'run_version'], name='segmentatio_segment_c223bd_idx'),
        ),
        migrations.AddField(
            model_name='countbox',
            name='segmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_boxes', to='segmentation.imagesegmentation'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='segmentation.segmentobject'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='segmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='segmentation.imagesegmentation'),
        ),
        migrations.AddField(
            model_name='segmentationresultversion',
            name='segmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_versions', to='segmentation.imagesegmentation'),
        ),
        migrations.AddIndex(
            model_name='countbox',
            index=models.Index(fields=['segmentation', 'run_version'], name='segmentatio_segment_c7bb39_idx'),
        ),
        migrations.AddConstraint(
            model_name='countbox',
            constraint=models.UniqueConstraint(fields=('segmentation', 'run_version'), name='uniq_count_box_per_result_version'),
        ),
        migrations.AddConstraint(
            model_name='countbox',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0), ('height__gt', 0)), name='count_box_has_area'),
        ),
        migrations.AddConstraint(
            model_name='countbox',
            constraint=models.CheckConstraint(condition=models.Q(('n_matched__lte', models.F('n_marked'))), name='count_box_matched_within_marked'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['segmentation', 'run_version', 'kind'], name='segmentatio_segment_5d4f0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitycheck',
            constraint=models.UniqueConstraint(fields=('segmentation', 'run_version', 'kind', 'ordinal'), name='uniq_quality_check_slot'),
        ),
        migrations.AddConstraint(
            model_name='qualitycheck',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answer', ''), ('answered_at__isnull', True)), models.Q(models.Q(('answer', ''), _negated=True), ('answered_at__isnull', False)), _connector='OR'), name='quality_check_answer_and_time_together'),
        ),
        migrations.AddIndex(
            model_name='segmentationresultversion',
            index=models.Index(fields=['segmentation', '-version'], name='segmentatio_segment_52e9f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='segmentationresultversion',
            constraint=models.UniqueConstraint(fields=('segmentation', 'version'), name='uniq_result_version_per_segmentation'),
        ),
        # Last, because it writes to four columns the operations above create.
        # Reverse is a no-op: unapplying this migration drops those columns.
        migrations.RunPython(
            backfill_probability_map_provenance,
            migrations.RunPython.noop,
            elidable=False,
        ),
    ]
