# Generated by Django 5.2.17 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("segmentation", "0004_alter_imagesegmentation_status_stage")]

    operations = [
        migrations.AddField(
            model_name="imagesegmentation",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RemoveConstraint(
            model_name="imagesegmentation",
            name="unique_segmentation_per_asset",
        ),
        migrations.AddConstraint(
            model_name="imagesegmentation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("asset__isnull", False)),
                fields=("asset", "segmentation_type", "display_name"),
                name="unique_segmentation_name_per_asset",
            ),
        ),
    ]
