# Generated by Django 5.2.17 on 2026-08-11

from django.db import migrations, models


def set_builtin_measurement_modes(apps, schema_editor):
    SegmentationType = apps.get_model("segmentation", "SegmentationType")
    SegmentationType.objects.filter(internal_name="quantem_internal_er").update(
        measurement_mode="global"
    )
    SegmentationType.objects.filter(internal_name="quantem_internal_tissue").update(
        measurement_mode="global"
    )
    SegmentationType.objects.filter(
        internal_name="quantem_internal_analysis_mask"
    ).update(measurement_mode="global")


class Migration(migrations.Migration):
    dependencies = [("segmentation", "0005_analysis_mask_names")]

    operations = [
        migrations.AddField(
            model_name="segmentationtype",
            name="measurement_mode",
            field=models.CharField(
                choices=[("objects", "Object-based"), ("global", "Global")],
                default="objects",
                max_length=16,
            ),
        ),
        migrations.RunPython(set_builtin_measurement_modes, migrations.RunPython.noop),
    ]
