# Generated by Django 5.2.17 on 2026-08-12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("segmentation", "0006_segmentationtype_measurement_mode")]

    operations = [
        migrations.AddField(
            model_name="imagesegmentation",
            name="final_result_provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="GlobalMask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=1024)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("foreground_pixels", models.PositiveBigIntegerField(default=0)),
                ("source", models.CharField(blank=True, default="", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "segmentation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_mask",
                        to="segmentation.imagesegmentation",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
