# Generated by Django 5.2.17 on 2026-08-13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("segmentation", "0007_global_masks_and_final_provenance")]

    operations = [
        migrations.CreateModel(
            name="AnalysisMaskObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=7)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("geometry_wkb", models.BinaryField(blank=True, null=True)),
                (
                    "segmentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_mask_objects",
                        to="segmentation.imagesegmentation",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["segmentation", "sort_order"],
                        name="seg_analysis_obj_sort_idx",
                    )
                ],
            },
        ),
    ]
