# Generated by Django 5.2.17 on 2026-08-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='segmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='segmentation.imagesegmentation'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['segmentation', '-created_at'], name='analysis_an_segment_32235f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status'], name='analysis_an_status_84ecd1_idx'),
        ),
    ]
