# Generated by Django 5.2.17 on 2026-08-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
        ('segmentation', '0002_segmentationcompletionarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='segmentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to='segmentation.imagesegmentation'),
        ),
    ]
