# Generated by Django 5.2.17 on 2026-08-07 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_model', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('mode', models.CharField(choices=[('threshold_only', 'Calibrated threshold only'), ('head', 'Head-only training')], default='threshold_only', max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('sweep', models.JSONField(blank=True, default=dict)),
                ('calibrated_threshold', models.FloatField(blank=True, null=True)),
                ('split_mode', models.CharField(choices=[('image-disjoint', 'Image-disjoint'), ('within-image', 'Within image'), ('no-heldout', 'No held-out data')], default='no-heldout', max_length=24)),
                ('head_path', models.CharField(blank=True, max_length=1024)),
                ('verified_reload', models.BooleanField(default=False)),
                ('trainable_params', models.BigIntegerField(blank=True, null=True)),
                ('train_seconds', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('segmentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adapters', to='segmentation.imagesegmentation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['segmentation', 'status'], name='finetune_ad_segment_a53ed4_idx'), models.Index(fields=['segmentation', 'applied_at'], name='finetune_ad_segment_78159a_idx')],
            },
        ),
    ]
