# Generated by Django 5.2.17 on 2026-08-11 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_datasets_asset_experiment'),
        ('finetune', '0001_initial'),
        ('library', '0001_initial'),
        ('segmentation', '0003_v2_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapter',
            name='cv_benchmark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adapter',
            name='cv_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='adapter',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adapters', to='library.experiment'),
        ),
        migrations.AddField(
            model_name='adapter',
            name='scope_assets',
            field=models.ManyToManyField(blank=True, related_name='adapters_scoped', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='adapter',
            name='scope_datasets',
            field=models.ManyToManyField(blank=True, related_name='adapters_scoped', to='library.dataset'),
        ),
        migrations.AddField(
            model_name='adapter',
            name='segmentation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adapters', to='segmentation.segmentationtype'),
        ),
        migrations.AddField(
            model_name='adapter',
            name='training_mode',
            field=models.CharField(choices=[('use_all', 'Use all'), ('holdout_1', 'Hold out one')], default='use_all', max_length=16),
        ),
        migrations.AddIndex(
            model_name='adapter',
            index=models.Index(fields=['segmentation_type', 'status'], name='finetune_ad_segment_d5659f_idx'),
        ),
        migrations.AddConstraint(
            model_name='adapter',
            constraint=models.UniqueConstraint(condition=models.Q(('segmentation_type__isnull', False), models.Q(('name', ''), _negated=True)), fields=('name', 'segmentation_type'), name='unique_finetune_name_per_organelle'),
        ),
    ]
