# Generated by Django 5.2.17 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_asset_datasets_asset_experiment"),
        ("finetune", "0002_scoped_named_finetunes"),
    ]

    operations = [
        migrations.AddField(
            model_name="adapter",
            name="applied_assets",
            field=models.ManyToManyField(
                blank=True,
                related_name="adapters_applied",
                to="assets.asset",
            ),
        ),
    ]
