# Generated by Django 5.2.17 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finetune", "0003_adapter_applied_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="adapter",
            name="preserves_live_version",
            field=models.BooleanField(default=False),
        ),
    ]
