# Generated by Django 5.2.17 on 2026-08-07 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifecycle_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('logical_width', models.PositiveIntegerField(blank=True, null=True)),
                ('logical_height', models.PositiveIntegerField(blank=True, null=True)),
                ('logical_depth', models.PositiveIntegerField(blank=True, null=True)),
                ('channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bit_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pixel_size_nm', models.FloatField(blank=True, null=True)),
                ('pixel_size_nm_z', models.FloatField(blank=True, null=True)),
                ('preprocess_stage', models.CharField(choices=[('NONE', 'Not started'), ('ENCODING', 'Encoding image / metadata'), ('FEATURES', 'Computing base features'), ('DONE', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], default='NONE', max_length=16)),
                ('preprocess_progress', models.FloatField(default=0.0)),
                ('preprocess_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['display_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rendition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('FULL', 'Full'), ('SUBSET', 'Subset'), ('NGFF', 'NGFF')], db_index=True, max_length=16)),
                ('storage_root', models.CharField(blank=True, default='', max_length=64)),
                ('stored_path', models.CharField(blank=True, default='', max_length=2048)),
                ('path_exists', models.BooleanField(default=False)),
                ('is_directory', models.BooleanField(default=False)),
                ('stored_width', models.PositiveIntegerField(blank=True, null=True)),
                ('stored_height', models.PositiveIntegerField(blank=True, null=True)),
                ('stored_depth', models.PositiveIntegerField(blank=True, null=True)),
                ('stored_channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stored_bit_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('z_plane_indices', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['asset__display_name', 'type', 'stored_path'],
            },
        ),
        migrations.CreateModel(
            name='ImageROI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AUTO', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rois', to='assets.asset')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
