# Generated by Django 5.2.17 on 2026-08-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageroi',
            name='segmentations',
            field=models.ManyToManyField(blank=True, related_name='rois', to='segmentation.imagesegmentation'),
        ),
        migrations.AddField(
            model_name='rendition',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renditions', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='rendition',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_renditions', to='assets.rendition'),
        ),
        migrations.AddIndex(
            model_name='rendition',
            index=models.Index(fields=['asset', 'type'], name='asset_rend_asset_type_idx'),
        ),
    ]
