# Generated by Django 5.2.17 on 2026-08-10, then commented by hand.
#
# Records the SHA-256 of the file each image was imported from, so importing
# the same file twice can be refused instead of quietly making a second image.
#
# Deliberately no data migration. The digest can only be taken from the source
# file, and the import pipeline deletes that file once it has written the
# canonical PNG -- so for images already in a library there is nothing left to
# hash. Existing rows keep the blank default, which never matches: the check
# recognises images imported from this version on, and says nothing at all
# about older ones rather than claiming they are different.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
