# Generated by Django 5.2.17 on 2026-08-10, then commented by hand.
#
# The other half of ``0003_asset_source_sha256``. That migration gave the
# library a way to recognise bytes it already holds; this one gives it a way to
# say so about a copy the user asked for anyway. When someone is told "you
# already have this image" and chooses to import it a second time regardless,
# the new row points at the one it duplicates.
#
# Null for every existing row and for every ordinary import, which is the
# honest answer: a first import is not a copy of anything, and images imported
# before this column existed were never asked the question.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_source_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_copies', to='assets.asset'),
        ),
    ]
