"""Combine CPU/CUDA payload manifests into NSIS and public release metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib.parse import quote

REPOSITORY_RELEASES = "https://github.com/ArrojoDrigoLab/QuantEM/releases/download"


def _load(path: Path) -> dict[str, object]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    required = {"version", "variant", "filename", "signature_filename", "sha256", "size"}
    missing = required.difference(payload)
    if missing:
        raise ValueError(f"{path.name} is missing {sorted(missing)}")
    return payload


def _nsis_value(value: object) -> str:
    result = str(value)
    if any(char in result for char in ('"', "\r", "\n", "$")):
        raise ValueError(f"value cannot be represented safely in NSIS: {result!r}")
    return result


def build_manifests(
    *,
    manifests: list[Path],
    tag: str,
    nsis_output: Path,
    json_output: Path,
    base_url: str = REPOSITORY_RELEASES,
    allow_unsigned: bool = False,
) -> dict[str, object]:
    variants: dict[str, dict[str, object]] = {}
    variant_paths: dict[str, Path] = {}
    for path in manifests:
        payload = _load(path)
        variant = str(payload["variant"])
        if variant not in {"cpu", "cuda"} or variant in variants:
            raise ValueError(f"unexpected or duplicate payload variant {variant!r}")
        variants[variant] = payload
        variant_paths[variant] = path
    if set(variants) != {"cpu", "cuda"}:
        raise ValueError("exactly one CPU and one CUDA payload manifest are required")

    versions = {str(payload["version"]) for payload in variants.values()}
    if len(versions) != 1:
        raise ValueError(f"payload versions do not match: {sorted(versions)}")
    version = versions.pop()
    if tag != f"v{version}":
        raise ValueError(f"tag {tag!r} does not match payload version {version!r}")

    public_variants: dict[str, dict[str, object]] = {}
    nsis_lines = [
        "; Generated by packaging/installer/build_payload_manifest.py. Do not edit.",
        f'!define QPAYLOAD_VERSION "{_nsis_value(version)}"',
    ]
    for variant in ("cpu", "cuda"):
        payload = variants[variant]
        filename = str(payload["filename"])
        signature_filename = str(payload["signature_filename"])
        # Manifests can arrive from different artifact directories, so resolve
        # the signature beside the manifest that declared this variant.
        declaring_path = variant_paths[variant]
        signature_path = declaring_path.parent / signature_filename
        signature = ""
        if signature_path.is_file():
            signature = signature_path.read_text(encoding="utf-8").strip()
        if not signature and not allow_unsigned:
            raise ValueError(f"missing or empty payload signature {signature_path}")
        prefix = f"QPAYLOAD_{variant.upper()}"
        nsis_lines.extend(
            [
                f'!define {prefix}_FILENAME "{_nsis_value(filename)}"',
                f'!define {prefix}_SHA256 "{_nsis_value(payload["sha256"])}"',
                f'!define {prefix}_SIZE "{_nsis_value(payload["size"])}"',
                f'!define {prefix}_SIZE_MB "{_nsis_value(payload.get("size_mb", "?"))}"',
            ]
        )
        parts = payload.get("parts")
        if not isinstance(parts, list) or not 1 <= len(parts) <= 4:
            raise ValueError(f"{variant} payload must contain between one and four parts")
        public_parts = []
        nsis_lines.append(f'!define {prefix}_PART_COUNT "{len(parts)}"')
        for index, part in enumerate(parts, start=1):
            if not isinstance(part, dict) or not {"filename", "sha256", "size"}.issubset(part):
                raise ValueError(f"invalid {variant} payload part {index}")
            part_url = f"{base_url.rstrip('/')}/{quote(tag)}/{quote(str(part['filename']))}"
            nsis_lines.extend(
                [
                    f'!define {prefix}_PART{index}_URL "{_nsis_value(part_url)}"',
                    f'!define {prefix}_PART{index}_SHA256 "{_nsis_value(part["sha256"])}"',
                ]
            )
            public_parts.append({**part, "url": part_url})
        public_variants[variant] = {
            **payload,
            "parts": public_parts,
            "signature": signature,
        }
    cuda_api = variants["cuda"].get("cuda_driver_api")
    if not isinstance(cuda_api, int) or cuda_api <= 0:
        raise ValueError("CUDA payload has no valid cuda_driver_api")
    nsis_lines.append(f'!define QPAYLOAD_CUDA_MIN_DRIVER_API "{cuda_api}"')

    nsis_output.parent.mkdir(parents=True, exist_ok=True)
    json_output.parent.mkdir(parents=True, exist_ok=True)
    nsis_output.write_text("\n".join(nsis_lines) + "\n", encoding="utf-8", newline="\n")
    public = {"schema": 1, "version": version, "tag": tag, "variants": public_variants}
    json_output.write_text(json.dumps(public, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return public


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, action="append", required=True)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--nsis-output", type=Path, required=True)
    parser.add_argument("--json-output", type=Path, required=True)
    parser.add_argument("--base-url", default=REPOSITORY_RELEASES)
    parser.add_argument("--allow-unsigned", action="store_true")
    args = parser.parse_args()
    build_manifests(
        manifests=args.manifest,
        tag=args.tag,
        nsis_output=args.nsis_output,
        json_output=args.json_output,
        base_url=args.base_url,
        allow_unsigned=args.allow_unsigned,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
