# Generated by Django 5.2.17 on 2026-08-07 05:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128)),
                ('priority', models.CharField(choices=[('high', 'High'), ('default', 'Default')], default='default', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('RETRY', 'Retry')], default='PENDING', max_length=16)),
                ('progress', models.FloatField(default=0.0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload_json', models.JSONField(default=dict)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('resource_class', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU')], default='cpu', max_length=16)),
                ('queue_name', models.CharField(default='default', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='jobs_job_status_007c84_idx'), models.Index(fields=['next_run_at'], name='jobs_job_next_ru_b36585_idx'), models.Index(fields=['resource_class'], name='jobs_job_resourc_d0b6d8_idx'), models.Index(fields=['queue_name'], name='jobs_job_queue_n_e0ff51_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('file_path', models.CharField(max_length=1024)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='jobs.job')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='info', max_length=16)),
                ('message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.job')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StorageArtifactLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_path', models.CharField(max_length=1024, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released')], default='ACTIVE', max_length=16)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_artifact_leases', to='jobs.job')),
            ],
            options={
                'ordering': ['artifact_path'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='jobs_storag_status_f558f1_idx'), models.Index(fields=['job', 'status'], name='jobs_storag_job_id_6da56b_idx')],
            },
        ),
    ]
