# Generated by Django 5.2.17 on 2026-08-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='progress_current_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='progress_total_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
